import { existsSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'

import type { Config } from '@/types/config'
import type { Context } from '@/types/context'
import type { Manifest, ManifestEntry } from '@/types/manifest'
import type { CommandModule } from '@/types/command'

import { parseAndCoerce } from '@/core/parser'
import { discoverManifest } from '@/core/discovery'
import { buildRouteLookup, resolveRoute } from '@/core/router'
import { createIo, createLogger } from '@/io/index'
import { closePrompts } from '@/io/prompt'

/**
 * Build a Manifest from a flat map of `route -> command module`.
 *
 * Routes are slash-delimited (`'users/list'` becomes `['users', 'list']`), which
 * is exactly what the router's longest-prefix matcher expects. In a real project
 * this manifest is code-generated by scanning the commands directory; demos and
 * tests build it inline so everything stays in one readable file.
 */
export function defineManifest(routes: Record<string, CommandModule>): Manifest {
  return {
    entries: Object.entries(routes).map(([key, module]) => ({
      route: key.split('/'),
      sourcePath: `${key}.ts`,
      importer: () => Promise.resolve({ default: module }),
      meta: module.meta,
    })),
  }
}

/**
 * Dispatch a command using `config.manifest` if present, otherwise auto-discover
 * one from `config.commandsDir`, resolved relative to the caller's location
 * (`importMeta.dir`). `importMeta` is only required when discovery is needed.
 *
 * Sets `process.exitCode` to the resolved code so entrypoints can just call
 * `void run(config)` instead of `process.exit(await run(config))`. This only
 * happens when `argv` is omitted (the entrypoint case); callers passing an
 * explicit `argv` (e.g. tests) get the exit code back without the side effect.
 *
 * When `CONCISE_TI_EXTRACT_MANIFEST` is set, dispatch is skipped entirely in
 * favor of writing the resolved manifest to that path as JSON. `concise-ti
 * compile` sets this to read a `commandsDir` CLI's manifest ahead of time,
 * without requiring entrypoints to change how they call `run()`.
 *
 * `ConfigType` lets a CLI with its own `Config` fields (see `demos/api-client`)
 * call `run<MyConfig>(config, import.meta)`; commands then declare
 * `command<Flags, MyConfig>()` to get a typed `ctx.config` with no cast.
 */
export async function run<ConfigType extends Config = Config>(
  config: ConfigType,
  importMeta?: { dir: string },
  argv?: string[],
): Promise<number> {
  const extractPath = process.env.CONCISE_TI_EXTRACT_MANIFEST

  const exitCode = extractPath
    ? await extractManifest(config, importMeta, extractPath)
    : await dispatch(config, importMeta, argv)

  if (argv === undefined) process.exitCode = exitCode

  return exitCode
}

async function extractManifest(
  config: Config,
  importMeta: { dir: string } | undefined,
  outPath: string,
): Promise<number> {
  if (config.manifest) {
    writeFileSync(outPath, JSON.stringify({ inline: true }))
    return 0
  }

  if (!importMeta?.dir) {
    console.error(
      'Error: discovering commands from config.commandsDir requires passing import.meta (with a dir) as the second argument to run().',
    )
    return 1
  }

  const resolvedCommandsDir = resolveCommandsDir(importMeta.dir, config.commandsDir ?? 'commands')

  try {
    const manifest = await discoverManifest(resolvedCommandsDir),
      entries = manifest.entries.map((entry) => ({
        route: entry.route,
        sourcePath: entry.sourcePath,
        meta: entry.meta ?? null,
      }))

    writeFileSync(outPath, JSON.stringify({ inline: false, entries }))
    return 0
  } catch (error) {
    console.error(
      `Error: failed to discover commands in "${resolvedCommandsDir}": ${error instanceof Error ? error.message : String(error)}`,
    )
    return 1
  }
}

/**
 * Resolve the effective commands directory for auto-discovery. Falls back to
 * the parent directory when the entrypoint lives in a subdirectory but
 * `commands/` sits at the project root.
 */
export function resolveCommandsDir(importMetaDir: string, commandsDir: string): string {
  const resolved = join(importMetaDir, commandsDir)

  if (existsSync(resolved)) return resolved

  const parentCommandsDir = join(dirname(importMetaDir), commandsDir)

  return existsSync(parentCommandsDir) ? parentCommandsDir : resolved
}

/** A compiled `bun build --compile` binary runs against a virtual filesystem
 * mounted at `/$bunfs/`, where `discoverManifest`'s directory scan finds
 * nothing. `concise-ti compile` pre-populates `generated-manifest.ts` for
 * exactly this case. */
function isCompiledBinaryDir(dir: string): boolean {
  return dir.startsWith('/$bunfs/')
}

/** Resolve `config.manifest`, or auto-discover one from `config.commandsDir`. */
async function resolveManifest(
  config: Config,
  importMeta?: { dir: string },
): Promise<Manifest | number> {
  if (config.manifest) return config.manifest

  if (!importMeta?.dir) {
    console.error(
      'Error: discovering commands from config.commandsDir requires passing import.meta (with a dir) as the second argument to run().',
    )
    return 1
  }

  if (isCompiledBinaryDir(importMeta.dir)) {
    const generated = (await import('@/core/generated-manifest')) as {
      default: Manifest
      generated: boolean
    }

    if (!generated.generated) {
      console.error(
        "Error: this binary was compiled with `bun build --compile` directly. A commandsDir CLI must be compiled with `concise-ti compile` instead, since discoverManifest cannot scan a compiled binary's virtual filesystem.",
      )
      return 1
    }

    return generated.default
  }

  const resolvedCommandsDir = resolveCommandsDir(importMeta.dir, config.commandsDir ?? 'commands')

  try {
    return await discoverManifest(resolvedCommandsDir)
  } catch (error) {
    console.error(
      `Error: failed to discover commands in "${resolvedCommandsDir}": ${error instanceof Error ? error.message : String(error)}`,
    )
    return 1
  }
}

/** Run the resolved command and translate its outcome (or a thrown error) into an exit code. */
async function invokeCommand(
  command: CommandModule,
  entry: Manifest['entries'][number],
  remaining: string[],
  config: Config,
  io: ReturnType<typeof createIo>,
  logger: ReturnType<typeof createLogger>,
): Promise<number> {
  try {
    const parsed = command.rawArgs
        ? { values: {}, positionals: remaining }
        : parseAndCoerce(remaining, command.flags ?? {}),
      context: Context = {
        flags: parsed.values,
        positionals: parsed.positionals,
        route: entry.route,
        cwd: process.cwd(),
        env: process.env,
        config,
        io,
        logger,
      }

    const result = await command.run(context)

    return typeof result === 'number' ? result : 0
  } catch (error) {
    io.writeError(`Error: ${error instanceof Error ? error.message : String(error)}`)

    return 1
  } finally {
    // Once ctx.io.prompt/confirm/select read from a real readline interface
    // instead of resolving instantly, leaving it open after dispatch would
    // keep the process alive (holding a listener on stdin) whether or not
    // this particular command ever prompted.
    closePrompts()
  }
}

/** `<bin> <version> (built with concise-ti)`, shared by the default `help` and `version` commands. */
function formatHeading(config: Config): string {
  return `${config.bin} ${config.version} (built with concise-ti)`
}

/**
 * Builds the default `help` command, listing every non-hidden route in `entries`.
 * `entryRoute` is the slash-delimited route dispatched to for empty argv (`config.entry`,
 * default `'help'`); when it isn't the default, the listing notes it explicitly.
 */
function buildHelpCommand(entries: ManifestEntry[], entryRoute: string): CommandModule {
  return {
    meta: { description: 'Show available commands' },
    flags: { json: { type: 'boolean', description: 'Output as JSON' } },
    run(ctx) {
      const visible = entries.filter((entry) => !entry.meta?.hidden)

      if (ctx.flags.json) {
        ctx.io.write(
          JSON.stringify({
            name: ctx.config.bin,
            version: ctx.config.version,
            commands: visible.map((entry) => ({
              route: entry.route.join('/'),
              description: entry.meta?.description ?? null,
            })),
            entry: entryRoute,
          }),
        )

        return 0
      }

      const width = visible.reduce((max, entry) => Math.max(max, entry.route.join('/').length), 0),
        lines = [formatHeading(ctx.config), '', 'Commands:']

      for (const entry of visible) {
        const route = entry.route.join('/'),
          description = entry.meta?.description

        lines.push(description ? `  ${route.padEnd(width + 2)}${description}` : `  ${route}`)
      }

      lines.push('')

      if (entryRoute !== 'help') lines.push('', `Running with no arguments invokes: ${entryRoute}`)

      ctx.io.write(lines.join('\n'))

      return 0
    },
  }
}

/** Builds the default `version` command. */
function buildVersionCommand(): CommandModule {
  return {
    meta: { description: 'Show CLI version' },
    run(ctx) {
      ctx.io.write(formatHeading(ctx.config))

      return 0
    },
  }
}

/**
 * Appends default `help`/`version` entries to `entries` (filtered by `config.skip`)
 * for any of those routes not already defined, overridden, or skipped. The `help`
 * listing reflects the final entry set, defaults included, and notes `entryRoute`
 * when it overrides the default empty-argv target.
 */
function withDefaultCommands(
  entries: ManifestEntry[],
  config: Config,
  entryRoute: string,
): ManifestEntry[] {
  const skip = new Set(config.skip ?? []),
    existingRoutes = new Set(entries.map((entry) => entry.route.join('/'))),
    finalEntries = [...entries]

  if (!skip.has('help') && !existingRoutes.has('help'))
    finalEntries.push({
      route: ['help'],
      sourcePath: '<default:help>',
      importer: () => Promise.resolve({ default: buildHelpCommand(finalEntries, entryRoute) }),
      meta: { description: 'Show available commands' },
    })

  if (!skip.has('version') && !existingRoutes.has('version'))
    finalEntries.push({
      route: ['version'],
      sourcePath: '<default:version>',
      importer: () => Promise.resolve({ default: buildVersionCommand() }),
      meta: { description: 'Show CLI version' },
    })

  return finalEntries
}

/**
 * Validates and normalizes `config.entry` into its raw slash-delimited route string
 * (default `'help'`). Only checks shape (non-empty, no leading/trailing/double
 * slashes) — existence against the resolved manifest is checked separately by
 * `assertEntryResolves`, once the final entry set (including defaults) is known.
 */
function resolveEntryRoute(config: Config): string {
  const raw = config.entry

  if (raw === undefined) return 'help'

  if (raw.trim().length === 0)
    throw new Error('Invalid config.entry: must be a non-empty, non-whitespace string')

  const segments = raw.split('/')

  if (raw !== raw.trim() || segments.some((segment) => segment.length === 0))
    throw new Error(
      `Invalid config.entry: "${raw}" must not have leading, trailing, or double slashes`,
    )

  return raw
}

/**
 * Ensures `entryRoute` names an existing, non-skipped route in the final entry
 * set. Throws rather than silently falling through to "Unknown command", since
 * a bad `config.entry` is a config authoring mistake, not a user input error.
 */
function assertEntryResolves(
  entryRoute: string,
  skip: Set<string>,
  lookup: Map<string, ManifestEntry>,
): void {
  if (skip.has(entryRoute))
    throw new Error(`Invalid config.entry: "${entryRoute}" is also listed in config.skip`)

  if (!lookup.has(entryRoute))
    throw new Error(`Invalid config.entry: "${entryRoute}" does not match any known route`)
}

async function dispatch(
  config: Config,
  importMeta?: { dir: string },
  argv?: string[],
): Promise<number> {
  const manifest = await resolveManifest(config, importMeta)

  if (typeof manifest === 'number') return manifest

  const resolvedArgv = argv ?? Bun.argv.slice(2)

  const io = createIo(),
    logger = createLogger()

  // Use name as default for bin if not provided
  if (!config.bin) config.bin = config.name

  const skip = new Set(config.skip ?? []),
    entryRoute = resolveEntryRoute(config),
    filteredEntries = manifest.entries.filter((entry) => !skip.has(entry.route.join('/'))),
    entries = withDefaultCommands(filteredEntries, config, entryRoute),
    lookup = buildRouteLookup({ entries })

  if (config.entry !== undefined) assertEntryResolves(entryRoute, skip, lookup)

  const argvForMatch = resolvedArgv.length > 0 ? resolvedArgv : entryRoute.split('/')

  const match = resolveRoute(argvForMatch, lookup)

  if (!match) {
    io.writeError(`Unknown command: ${resolvedArgv.join(' ') || '(none)'}`)
    return 1
  }

  const { entry, remaining } = match,
    command = (await entry.importer()).default

  return invokeCommand(command, entry, remaining, config, io, logger)
}
