import { existsSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'

import type { Config } from '@/types/config'
import type { Context } from '@/types/context'
import type { Manifest } from '@/types/manifest'
import type { CommandModule } from '@/types/command'

import { parseAndCoerce } from '@/core/parser'
import { discoverManifest } from '@/core/discovery'
import { buildRouteLookup, resolveRoute } from '@/core/router'
import { createIo, createLogger } from '@/io/index'

/**
 * Build a Manifest from a flat map of `route -> command module`.
 *
 * Routes are slash-delimited (`'users/list'` becomes `['users', 'list']`), which
 * is exactly what the router's longest-prefix matcher expects. In a real project
 * this manifest is code-generated by scanning the commands directory; demos and
 * tests build it inline so everything stays in one readable file.
 */
export function defineManifest(routes: Record<string, CommandModule>): Manifest {
  return {
    entries: Object.entries(routes).map(([key, module]) => ({
      route: key.split('/'),
      sourcePath: `${key}.ts`,
      importer: () => Promise.resolve({ default: module }),
      meta: module.meta,
    })),
  }
}

/**
 * Dispatch a command using `config.manifest` if present, otherwise auto-discover
 * one from `config.commandsDir`, resolved relative to the caller's location
 * (`importMeta.dir`). `importMeta` is only required when discovery is needed.
 *
 * Sets `process.exitCode` to the resolved code so entrypoints can just call
 * `void run(config)` instead of `process.exit(await run(config))`. This only
 * happens when `argv` is omitted (the entrypoint case); callers passing an
 * explicit `argv` (e.g. tests) get the exit code back without the side effect.
 *
 * When `CONCISE_TI_EXTRACT_MANIFEST` is set, dispatch is skipped entirely in
 * favor of writing the resolved manifest to that path as JSON. `concise-ti
 * compile` sets this to read a `commandsDir` CLI's manifest ahead of time,
 * without requiring entrypoints to change how they call `run()`.
 */
export async function run(
  config: Config,
  importMeta?: { dir: string },
  argv?: string[],
): Promise<number> {
  const extractPath = process.env.CONCISE_TI_EXTRACT_MANIFEST

  const exitCode = extractPath
    ? await extractManifest(config, importMeta, extractPath)
    : await dispatch(config, importMeta, argv)

  if (argv === undefined) process.exitCode = exitCode

  return exitCode
}

async function extractManifest(
  config: Config,
  importMeta: { dir: string } | undefined,
  outPath: string,
): Promise<number> {
  if (config.manifest) {
    writeFileSync(outPath, JSON.stringify({ inline: true }))
    return 0
  }

  if (!importMeta?.dir) {
    console.error(
      'Error: discovering commands from config.commandsDir requires passing import.meta (with a dir) as the second argument to run().',
    )
    return 1
  }

  const resolvedCommandsDir = resolveCommandsDir(importMeta.dir, config.commandsDir ?? 'commands')

  try {
    const manifest = await discoverManifest(resolvedCommandsDir),
      entries = manifest.entries.map((entry) => ({
        route: entry.route,
        sourcePath: entry.sourcePath,
        meta: entry.meta ?? null,
      }))

    writeFileSync(outPath, JSON.stringify({ inline: false, entries }))
    return 0
  } catch (error) {
    console.error(
      `Error: failed to discover commands in "${resolvedCommandsDir}": ${error instanceof Error ? error.message : String(error)}`,
    )
    return 1
  }
}

/**
 * Resolve the effective commands directory for auto-discovery. Falls back to
 * the parent directory when the entrypoint lives in a subdirectory but
 * `commands/` sits at the project root.
 */
export function resolveCommandsDir(importMetaDir: string, commandsDir: string): string {
  const resolved = join(importMetaDir, commandsDir)

  if (existsSync(resolved)) return resolved

  const parentCommandsDir = join(dirname(importMetaDir), commandsDir)

  return existsSync(parentCommandsDir) ? parentCommandsDir : resolved
}

/** A compiled `bun build --compile` binary runs against a virtual filesystem
 * mounted at `/$bunfs/`, where `discoverManifest`'s directory scan finds
 * nothing. `concise-ti compile` pre-populates `generated-manifest.ts` for
 * exactly this case. */
function isCompiledBinaryDir(dir: string): boolean {
  return dir.startsWith('/$bunfs/')
}

/** Resolve `config.manifest`, or auto-discover one from `config.commandsDir`. */
async function resolveManifest(
  config: Config,
  importMeta?: { dir: string },
): Promise<Manifest | number> {
  if (config.manifest) return config.manifest

  if (!importMeta?.dir) {
    console.error(
      'Error: discovering commands from config.commandsDir requires passing import.meta (with a dir) as the second argument to run().',
    )
    return 1
  }

  if (isCompiledBinaryDir(importMeta.dir)) {
    const generated = (await import('@/core/generated-manifest')) as {
      default: Manifest
      generated: boolean
    }

    if (!generated.generated) {
      console.error(
        "Error: this binary was compiled with `bun build --compile` directly. A commandsDir CLI must be compiled with `concise-ti compile` instead, since discoverManifest cannot scan a compiled binary's virtual filesystem.",
      )
      return 1
    }

    return generated.default
  }

  const resolvedCommandsDir = resolveCommandsDir(importMeta.dir, config.commandsDir ?? 'commands')

  try {
    return await discoverManifest(resolvedCommandsDir)
  } catch (error) {
    console.error(
      `Error: failed to discover commands in "${resolvedCommandsDir}": ${error instanceof Error ? error.message : String(error)}`,
    )
    return 1
  }
}

/** Run the resolved command and translate its outcome (or a thrown error) into an exit code. */
async function invokeCommand(
  command: CommandModule,
  entry: Manifest['entries'][number],
  remaining: string[],
  config: Config,
  io: ReturnType<typeof createIo>,
  logger: ReturnType<typeof createLogger>,
): Promise<number> {
  try {
    const parsed = command.rawArgs
        ? { values: {}, positionals: remaining }
        : parseAndCoerce(remaining, command.flags ?? {}),
      context: Context = {
        flags: parsed.values,
        positionals: parsed.positionals,
        route: entry.route,
        cwd: process.cwd(),
        env: process.env,
        config,
        io,
        logger,
      }

    const result = await command.run(context)

    return typeof result === 'number' ? result : 0
  } catch (error) {
    io.writeError(`Error: ${error instanceof Error ? error.message : String(error)}`)

    return 1
  }
}

async function dispatch(
  config: Config,
  importMeta?: { dir: string },
  argv?: string[],
): Promise<number> {
  const manifest = await resolveManifest(config, importMeta)

  if (typeof manifest === 'number') return manifest

  const resolvedArgv = argv ?? Bun.argv.slice(2)

  const io = createIo(),
    logger = createLogger()

  // Use name as default for bin if not provided
  if (!config.bin) config.bin = config.name

  const match = resolveRoute(resolvedArgv, buildRouteLookup(manifest))

  if (!match) {
    io.writeError(`Unknown command: ${resolvedArgv.join(' ') || '(none)'}`)
    return 1
  }

  const { entry, remaining } = match,
    command = (await entry.importer()).default

  return invokeCommand(command, entry, remaining, config, io, logger)
}
